export const BODY_1 = 'body1'
export const BODY_2 = 'body2'
export const SECONDARY = 'secondary'
export const AVATAR = 'avatar'
export const SUBTITLE2 = 'subtitle2'
export const H3 = 'h3'
export const LARGE = 'large'
export const COVER = 'cover'
